name: "Clientcide-Tests"

description: "Tests for the Clientcide"

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

sources:
  - "Behaviors/Behavior.Autocompleter.js"
  - "Behaviors/Behavior.Tabs.js"
  - "Behaviors/Behavior.Tips.js"
